const DemoData = {
  columns: [
    {
      id: 'city',
      ordinalNo: 4,
      title: 'City',
      type: 'string',
      width: 120,
    },
    {
      id: 'phone',
      ordinalNo: 7,
      title: 'Phone number',
      type: 'string',
      width: 140,
    },
    {
      id: 'country',
      ordinalNo: 5,
      title: 'Country',
      type: 'select',
      width: 140,
    },
    {
      id: 'id',
      ordinalNo: 1,
      title: 'User ID',
      type: 'string',
      width: 60,
    },
    {
      id: 'active',
      ordinalNo: 8,
      title: 'Active',
      type: 'boolean',
      width: 50,
    },
    {
      id: 'name',
      ordinalNo: 2,
      title: 'Full name',
      type: 'string',
      width: 150,
    },
    {
      id: 'age',
      ordinalNo: 3,
      title: 'Age',
      type: 'number',
      width: 50,
    },
    {
      id: 'email',
      ordinalNo: 6,
      title: 'Email address',
      type: 'string',
      width: 100,
    },
  ],
  data: [
    {
      id: 1,
      name: 'Sabir Imanov',
      age: 31,
      email: 'sabir@promote.az',
      city: 'Willmington',
      country: ['US', 'AZ', 'IL'],
    },
    {
      id: 2,
      name: 'John Anderson',
      email: 'john@gmail.com',
      country: ['AZ', 'IL', 'US'],
      phone: '+44300000000',
      active: true,
    },
    {
      id: 3,
      name: 'Michael Whilliams',
      age: 20,
      city: 'Paris',
      phone: '+19454000000',
    },
    {
      id: 4,
      age: 47,
      email: 'anna@test.com',
      city: 'Jerusalem',
      country: ['IL', 'US', 'AZ'],
      phone: '+972500000000',
      active: false,
    },
    {
      id: 5,
      name: 'Sabir Imanov',
      age: 31,
      email: 'sabir@promote.az',
      city: 'Willmington',
      country: ['US', 'AZ', 'IL'],
    },
    {
      id: 6,
      name: 'John Anderson',
      email: 'john@gmail.com',
      country: ['AZ', 'IL', 'US'],
      phone: '+44300000000',
      active: true,
    },
    {
      id: 7,
      name: 'Michael Whilliams',
      age: 20,
      city: 'Paris',
      phone: '+19454000000',
    },
    {
      id: 8,
      age: 47,
      email: 'anna@test.com',
      city: 'Jerusalem',
      country: ['IL', 'US', 'AZ'],
      phone: '+972500000000',
      active: false,
    },
    {
      id: 9,
      name: 'Sabir Imanov',
      age: 31,
      email: 'sabir@promote.az',
      city: 'Willmington',
      country: ['US', 'AZ', 'IL'],
    },
    {
      id: 10,
      name: 'John Anderson',
      email: 'john@gmail.com',
      country: ['AZ', 'IL', 'US'],
      phone: '+44300000000',
      active: true,
    },
    {
      id: 11,
      name: 'Michael Whilliams',
      age: 20,
      city: 'Paris',
      phone: '+19454000000',
    },
    {
      id: 12,
      age: 47,
      email: 'anna@test.com',
      city: 'Jerusalem',
      country: ['IL', 'US', 'AZ'],
      phone: '+972500000000',
      active: false,
    },
    {
      id: 13,
      name: 'Sabir Imanov',
      age: 31,
      email: 'sabir@promote.az',
      city: 'Willmington',
      country: ['US', 'AZ', 'IL'],
    },
    {
      id: 14,
      name: 'John Anderson',
      email: 'john@gmail.com',
      country: ['AZ', 'IL', 'US'],
      phone: '+44300000000',
      active: true,
    },
    {
      id: 15,
      name: 'Michael Whilliams',
      age: 20,
      city: 'Paris',
      phone: '+19454000000',
    },
    {
      id: 16,
      age: 47,
      email: 'anna@test.com',
      city: 'Jerusalem',
      country: ['IL', 'US', 'AZ'],
      phone: '+972500000000',
      active: false,
    },
  ],
};
export default DemoData;
